services:
  client:
    build: ./client
    depends_on:
      - server
    networks:
      - app-network

  server:
    build: ./server
    depends_on:
      - mysql
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    networks:
      - app-network

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_DATABASE: collabity_v1
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./client/dist:/usr/share/nginx/html
    depends_on:
      - client
      - server
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
